name: Deploy Streamlit to Azure Web App

on:
  push:
    branches:
      - dev
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: "Choose deployment environment"
        required: true
        default: "production"
        type: choice
        options:
          - production

jobs:
  deploy-to-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Startup Command
        uses: azure/appservice-settings@v1
        with:
          app-name: mini-inventory-app-dev
          general-settings-json: |
            {
              "linuxFxVersion": "PYTHON|3.10",
              "startupCommand": "bash startup.txt"
            }

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: mini-inventory-app
          package: .

  deploy-to-prod:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Startup Command
        uses: azure/appservice-settings@v1
        with:
          app-name: mini-inventory-app
          general-settings-json: |
            {
            "linuxFxVersion": "PYTHON|3.10",
            "startupCommand": "bash startup.txt"
            }

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: mini-inventory-app
          package: .
