name: CI/CD Pipeline for Mini Inventory App

on:
  push:
    branches: [main] # Deploy only when pushing to main
  workflow_dispatch: # Manual trigger in GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run basic checks (optional)
        run: |
          python -m py_compile app/main.py

      - name: Run migration on Azure SQL
        run: |
          sqlcmd -S ${{ secrets.AZURE_SQL_SERVER }}
                 -d ${{ secrets.AZURE_SQL_DATABASE }}
                 -U ${{ secrets.AZURE_SQL_USER }}
                 -P ${{ secrets.AZURE_SQL_PASSWORD }}
                 -i db/schema.sql

      - name: Deploy app
        run: echo "Simulated app deployment"
